version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql_test_db

  tests-postgres:
    build: .
    image: tinypool
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: nimble testPostgresContainedCmd

  tests-sqlite:
    build: .
    image: tinypool
    volumes:
      - .:/usr/src/app
    command: nimble testSqliteContainerCmd

  tests-mysql:
    build: .
    image: tinypool
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    command: nimble testMysqlContainerCmd